{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set version = version.lstrip('v') %}

package:
  name: filmaffinity-backup
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -v

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.9
    - requests
    - beautifulsoup4
    - click
    - pandas
    - rich
    - typer
    - selenium
    - webdriver-manager
    - cinemagoer

test:
  imports:
    - filmaffinity
    - imdb_uploader
  source_files:
    - tests
    - pyproject.toml
  commands:
    - pwd
    - ls -la
    - python -m pytest -v -m "not integration" tests/
  requires:
    - pytest
    - pytest-cov

about:
  home: https://github.com/oyale/filmaffinity-backup
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: "Backup and export your FilmAffinity data."
  description: |
    A tool to backup and export your FilmAffinity data, including support for exporting to various formats and uploading to IMDb and Letterboxd.
  dev_url: https://github.com/oyale/filmaffinity-backup
  doc_url: https://github.com/oyale/filmaffinity-backup

extra:
  recipe-maintainers:
    - oyale
