name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project is affected?
      options:
        - FilmAffinity Backup (fa-backup)
        - IMDb Uploader (fa-upload)
        - Both
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you using? (run `pip show filmaffinity-backup`)
      placeholder: e.g., 1.0.0
    validations:
      required: false

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Which Python version are you using? (run `python --version`)
      placeholder: e.g., Python 3.11.5
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g., Ubuntu 22.04, macOS 13.5, Windows 11
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error messages or logs
      placeholder: Paste error logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any additional information...
    validations:
      required: false
